# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import secondpage
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.mainframe = QtWidgets.QFrame(self.gridLayoutWidget)
        self.mainframe.setStyleSheet("border-image: url(:/images/images/background.jpeg) 0 0 0 0 stretch stretch;;")
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.startbutton = QtWidgets.QPushButton(self.mainframe)
        self.startbutton.setGeometry(QtCore.QRect(325, 200, 161, 151))
        self.startbutton.setStyleSheet("border-image:url(:/images/images/play-button.png) 0 0 0 0 stretch")
        self.startbutton.setText("")
        self.startbutton.setObjectName("startbutton")
        self.label = QtWidgets.QLabel(self.mainframe)
        self.label.setGeometry(QtCore.QRect(327, 352, 211, 71))
        self.label.setStyleSheet("\n"
"color:rgb(255, 255, 255);\n"
"border-image:none;\n"
"font: 75 28pt \"Arial\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.mainframe)
        self.label_2.setGeometry(QtCore.QRect(370, 390, 111, 71))
        self.label_2.setStyleSheet("font: 14pt \"Arial\";\n"
"border-image:none;\n"
"color: rgb(0, 255, 226)")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.mainframe, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MainWindow=MainWindow
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Let\'s Start"))
        self.label_2.setText(_translate("MainWindow", "a Workout"))
        self.startbutton.clicked.connect(self.exerciseWindow)
        


    def exerciseWindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=secondpage.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
