# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import thirdpage
import resources2_rc

class Exercise():
    def __init__(self):
        self.heading=None
        self.subheading=None
        self.description=None
        self.image=None
        self.command=None
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 900, 700))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Mainframe = QtWidgets.QFrame(self.gridLayoutWidget)
        self.Mainframe.setStyleSheet("Background:black")
        self.Mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Mainframe.setObjectName("Mainframe")
        self.label = QtWidgets.QLabel(self.Mainframe)
        self.label.setGeometry(QtCore.QRect(20, 40, 441, 91))
        self.label.setStyleSheet("font: 36pt \"Arial\";\n"
"color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Mainframe)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 131, 61))
        self.label_2.setStyleSheet("font: 12pt \"Arial\";\n"
"color: rgb(0, 255, 226)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Mainframe)
        self.label_3.setGeometry(QtCore.QRect(220, 120, 111, 41))
        self.label_3.setStyleSheet("font: 12pt \"Arial\";\n"
"color: rgb(0, 255, 226)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Mainframe)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 21, 21))
        self.label_4.setStyleSheet("border-image: url(:/images/images/rec.png) 0 0 0 0 stretch stretch;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Mainframe)
        self.label_5.setGeometry(QtCore.QRect(190, 130, 21, 21))
        self.label_5.setStyleSheet("border-image: url(:/images/images/rec.png) 0 0 0 0 stretch stretch;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Mainframe)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 200, 800, 450))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Innerframe = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.Innerframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Innerframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Innerframe.setObjectName("Innerframe")
        self.shoulderbutton = QtWidgets.QPushButton(self.Innerframe)
        self.shoulderbutton.setGeometry(QtCore.QRect(40, 10, 700, 120))
        self.shoulderbutton.setStyleSheet("Background:black;\n"
"font: 24pt \"Arial\";\n"
"border-radius:30px;\n"
"border: 2px solid black;\n"
"border-color:rgb(0, 255, 226);\n"
"color:white;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"\n"
"")
        self.shoulderbutton.setObjectName("shoulderbutton")
        self.bicepbutton = QtWidgets.QPushButton(self.Innerframe)
        self.bicepbutton.setGeometry(QtCore.QRect(40, 160, 700, 120))
        self.bicepbutton.setStyleSheet("Background:black;\n"
"font: 24pt \"Arial\";\n"
"border-radius:30px;\n"
"border: 2px solid black;\n"
"border-color:rgb(0, 255, 226);\n"
"color:white;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"\n"
"")
        self.bicepbutton.setObjectName("bicepbutton")
        self.tricepbutton = QtWidgets.QPushButton(self.Innerframe)
        self.tricepbutton.setGeometry(QtCore.QRect(40, 300, 700, 120))
        self.tricepbutton.setStyleSheet("Background:black;\n"
"font: 24pt \"Arial\";\n"
"border-radius:30px;\n"
"border: 2px solid black;\n"
"border-color:rgb(0, 255, 226);\n"
"color:white;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"\n"
"")
        self.tricepbutton.setObjectName("tricepbutton")
        self.label_7 = QtWidgets.QLabel(self.Innerframe)
        self.label_7.setGeometry(QtCore.QRect(450, 170, 260, 100))
        self.label_7.setStyleSheet("\n"
"\n"
"border-image:url(:/images/images/pngaaa.com-314602.png);\n"
"background-color:transparent;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Innerframe)
        self.label_8.setGeometry(QtCore.QRect(450, 310, 260, 100))
        self.label_8.setStyleSheet("\n"
"\n"
"border-image:url(:/images/images/tricep1.png);\n"
"background-color:transparent;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.Innerframe)
        self.label_6.setGeometry(QtCore.QRect(450, 20, 260, 100))
        self.label_6.setStyleSheet("border-image:url(:/images/images/shoulder1.png);\n"
"background-color:transparent;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.Innerframe)
        self.label_9.setGeometry(QtCore.QRect(100, 90, 91, 41))
        self.label_9.setStyleSheet("color:yellow;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"Background-color: transparent;")
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.Innerframe)
        self.label_12.setGeometry(QtCore.QRect(60, 100, 31, 21))
        self.label_12.setStyleSheet("border-image:url(:/images/images/graph.png);\n"
"background:transparent;\n"
"")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Innerframe)
        self.label_13.setGeometry(QtCore.QRect(60, 250, 31, 21))
        self.label_13.setStyleSheet("border-image:url(:/images/images/graph.png);\n"
"background:transparent;\n"
"")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Innerframe)
        self.label_14.setGeometry(QtCore.QRect(60, 390, 31, 21))
        self.label_14.setStyleSheet("border-image:url(:/images/images/graph.png);\n"
"background:transparent;\n"
"")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(self.Innerframe)
        self.label_10.setGeometry(QtCore.QRect(100, 240, 91, 41))
        self.label_10.setStyleSheet("color:yellow;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"Background-color: transparent;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Innerframe)
        self.label_11.setGeometry(QtCore.QRect(100, 380, 91, 41))
        self.label_11.setStyleSheet("color:yellow;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"Background-color: transparent;")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.Innerframe, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.Mainframe, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MainWindow=MainWindow
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Start a Workout"))
        self.label_2.setText(_translate("MainWindow", "Beginners"))
        self.label_3.setText(_translate("MainWindow", "Popular"))
        self.shoulderbutton.setText(_translate("MainWindow", "Shoulder"))
        self.bicepbutton.setText(_translate("MainWindow", "Biceps"))
        self.tricepbutton.setText(_translate("MainWindow", "Triceps"))
        self.label_9.setText(_translate("MainWindow", "Beginners"))
        self.label_10.setText(_translate("MainWindow", "Beginners"))
        self.label_11.setText(_translate("MainWindow", "Beginners"))

        #added
        self.shoulderbutton.clicked.connect(lambda: self.go_to_exercise("shoulder"))
        self.bicepbutton.clicked.connect(lambda: self.go_to_exercise("bicep"))
        self.tricepbutton.clicked.connect(lambda: self.go_to_exercise("tricep"))
        


    def go_to_exercise(self,name):
        basedir="E:\\minor_project\\project\\deeptrain\\tf-pose-estimation"
        exercise=Exercise()
        if(name=='shoulder'):
            exercise.heading="Shoulder"
            exercise.subheading="Shoulder Press"
            exercise.description="Lie on the bemch wiht a dumbbell in each hand and your feet flat on the floor. You can rest your feet up on the bench if it's more comfortable.Push the dumbbells up so that your arms are directly over your shoulders and your palms are up. Pull your abdominals in, and tilt your chin toward your chest.Lower the dumbbells down and a little to the side until your elbows are slightly below your shoulders.4.Roll your Shoulder blades back and down, like you're pinching them together and accentuating your chest.Push the weights back up, taking care to lock your elbows or allow your shoulder blades to rise off the bench."
            exercise.image="shoulderpress"
            exercise.command="python "+basedir+"\\statusbar.py --image=dumbbell.jpg --model=cmu --exercise=shoulder"

        elif(name=='bicep'):
            exercise.heading="Bicep"
            exercise.subheading="Bicep Curl"
            exercise.description="Take 2 dumbbells. Stand with you rlegs should with apart, bend your knees slightly. let your arms to hand down with your palms facing each other.Move only your forearms, slowly curl the dumbbells up to shoulder level. Turn your palms up when they pass your thighs. Keep your elbows pressed against your sides throughout the exercise."
            exercise.image="bicepcurl"
            exercise.command="python "+basedir+"\\statusbar.py --model=cmu --image=bicepcurl.jpg --exercise=bicep"

        elif(name=='tricep'):
            exercise.heading="Triceps"
            exercise.subheading="Pulley Push Down"
            exercise.description="Using a cable machine raise the pulley above your head, user the bar. Set your feet width apart,tuck our wlbows in and lean forward.Now move your hands up and down in a complete range of motion and make sure keep your hands in tight with your body."
            exercise.image="triceppush"
            exercise.command="python "+basedir+"\\statusbar.py --model=cmu --image=tricep-pushdown.jpg --exercise=tricep"


        self.window=QtWidgets.QMainWindow()
        self.ui=thirdpage.Ui_MainWindow(exercise)
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.close()
      
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
