# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thirdpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import secondpage
import resources3_rc
import os

class Ui_MainWindow(object):
    def __init__(self,exercise):
        self.exercise=exercise
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 900, 700))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setStyleSheet("background-color:black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 900, 700))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Backbutton = QtWidgets.QPushButton(self.frame_2)
        self.Backbutton.setGeometry(QtCore.QRect(10, 40, 50, 30))
        self.Backbutton.setStyleSheet("Border-image:url(:/images/images/Back.png)")
        self.Backbutton.setText("")
        self.Backbutton.setObjectName("Backbutton")
        self.topheading = QtWidgets.QLabel(self.frame_2)
        self.topheading.setGeometry(QtCore.QRect(100, 40, 200, 50))
        self.topheading.setStyleSheet("color:white;\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"")
        self.topheading.setObjectName("topheading")
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.subheading = QtWidgets.QLabel(self.frame)
        self.subheading.setGeometry(QtCore.QRect(70, 120, 700, 91))
        self.subheading.setStyleSheet("color:white;\n"
"font-size:30px;\n"
"border-radius:25px;\n"
"border:3px solid green;\n"
"border-color: rgb(0, 255, 226);\n"
"text-align:center;\n"
"")
        self.subheading.setObjectName("subheading")
        self.description = QtWidgets.QFrame(self.frame)
        self.description.setGeometry(QtCore.QRect(70, 250, 735, 300))
        self.description.setStyleSheet("border:3px solid white;\n"
"border-color: rgb(0, 255, 226);")
        self.description.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.description.setFrameShadow(QtWidgets.QFrame.Raised)
        self.description.setObjectName("description")
        self.exercise_image = QtWidgets.QLabel(self.description)
        self.exercise_image.setGeometry(QtCore.QRect(550, 50, 140, 200))
        self.exercise_image.setStyleSheet("border-image: url(:/images/images/"+self.exercise.image+".jpg);")
        self.exercise_image.setText("")
        self.exercise_image.setObjectName("exercise_image")
        self.Description = QtWidgets.QTextEdit(self.description)
        self.Description.setGeometry(QtCore.QRect(40, 50, 500, 200))
        self.Description.setStyleSheet("border:none;\n"
"background-color:white;\n"
"padding:10px;\n"
"text-align:justify;")
        self.Description.setObjectName("Description")
        self.actionbutton = QtWidgets.QPushButton(self.frame)
        self.actionbutton.setGeometry(QtCore.QRect(300, 580, 261, 61))
        self.actionbutton.setStyleSheet("border:2px solid white;\n"
"border-color:rgb(0,255,226);\n"
"border-radius:25px;\n"
"font-size:15px;\n"
"color:white;")
        self.actionbutton.setObjectName("actionbutton")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MainWindow=MainWindow
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.topheading.setText(_translate("MainWindow", self.exercise.heading))
        self.subheading.setText(_translate("MainWindow", "    "+self.exercise.subheading))
        self.Description.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Description</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">"+self.exercise.description+"</span></p></body></html>"))
        self.actionbutton.setText(_translate("MainWindow", "Open Camera"))
        self.Backbutton.clicked.connect(self.go_back)
        self.actionbutton.clicked.connect(self.call_func)

    def call_func(self):
        print(self.exercise.command)
        os.system(self.exercise.command)

    def go_back(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=secondpage.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.close()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
